core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("teams/", include("team.urls", namespace="team")),
    path("projects/", include("project.urls", namespace="project")),
    path("accounts/", include("account.urls", namespace="account")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

team/urls.py
from django.urls import path

from team.views import (
    TeamListView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    TeamDetailView,
)

urlpatterns = [
    path("", TeamListView.as_view(), name="team-list"),
    path("create/", TeamCreateView.as_view(), name="team-create"),
    path("detail/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("update/<int:pk>", TeamUpdateView.as_view(), name="team-update"),
    path("delete/<int:pk>", TeamDeleteView.as_view(), name="team-delete"),
]

app_name = "team"

team/models.py
from django.conf import settings
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="teams",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

team/forms.py
from django import forms

from account.models import Worker
from team.models import Team


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = (
            "name",
            "members",
        )
        widgets = {
            "members": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields["members"].queryset = Worker.objects.all()
            self.fields["members"].initial = [user]

team/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)

from team.forms import TeamForm
from team.models import Team


class TeamListView(LoginRequiredMixin, ListView):
    model = Team
    template_name = "team_pages/team_list.html"

    def get_queryset(self):
        return Team.objects.filter(members=self.request.user)


class TeamCreateView(LoginRequiredMixin, CreateView):
    model = Team
    template_name = "team_pages/team_form.html"
    form_class = TeamForm
    success_url = reverse_lazy("team:team-list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TeamDetailView(LoginRequiredMixin, DetailView):
    model = Team
    template_name = "team_pages/team_detail.html"


class TeamUpdateView(LoginRequiredMixin, UpdateView):
    model = Team
    template_name = "team_pages/team_form.html"
    form_class = TeamForm
    success_url = reverse_lazy("team:team-list")


class TeamDeleteView(LoginRequiredMixin, DeleteView):
    model = Team
    success_url = reverse_lazy("team:team-list")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.success_url)

templates/team_pages/team_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h2 class="mb-4">{{ team.name }}</h2>
    <p><strong>Author:</strong> {{ team.author }}</p>
    <h4>Members:</h4>
    <ul class="list-group mb-3">
      {% for member in team.members.all %}
        <li class="list-group-item">{{ member }}</li>
      {% empty %}
        <p class="text-muted">No members yet.</p>
      {% endfor %}
    </ul>

    {% if user == team.author %}
      <a href="{% url "team:team-update" team.id %}" class="btn btn-primary">Edit</a>
      <a href="{% url "team:team-delete" team.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
{% endblock %}

templates/team_pages/team_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} team</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/team_pages/team_list.html
{% extends "base.html" %}


{% block content %}
  <div>
    <h2 class="mb-4">Teams</h2>
    <a href="{% url "team:team-create" %}" class="btn btn-success mb-3">Create team</a>

    {% if team_list %}
      <div class="row">
        {% for team in team_list %}
          <div class="col-md-4 mb-3">
            <div class="card shadow-sm">
              <div class="card-body">
                <h5 class="card-title">{{ team.name }}</h5>
                <p class="card-text">Author: {{ team.author }}</p>
                <p class="card-text"><strong>Members:</strong> {{ team.members.count }}</p>
                <a href="{% url "team:team-detail" team.id %}" class="btn btn-primary">Detail</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p class="text-muted">No teams yet.</p>
    {% endif %}
  </div>
{% endblock %}