core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("teams/", include("team.urls", namespace="team")),
    path("projects/", include("project.urls", namespace="project")),
    path("accounts/", include("account.urls", namespace="account")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.urls import path

from project.views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectDeleteView,
    ProjectUpdateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="project-list"),
    path("create/", ProjectCreateView.as_view(), name="project-create"),
    path("project-detail/<int:pk>", ProjectDetailView.as_view(), name="project-detail"),
    path("delete/<int:pk>", ProjectDeleteView.as_view(), name="project-delete"),
    path("update/<int:pk>", ProjectUpdateView.as_view(), name="project-update"),
]

app_name = "project"

task/urls.py
from django.urls import path

from task.views import (
    Index,
    complete_task,
    CreatedTaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    create_task_view,
)

urlpatterns = [
    path("", Index.as_view(), name="task"),
    path("task/create/", create_task_view, name="task-create"),
    path("task/create/<int:project_id>/", create_task_view, name="task-project-create"),
    path("task/created-list/", CreatedTaskListView.as_view(), name="task-list-created"),
    path("task/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("task/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),
    path("task/detail/<int:pk>", TaskDetailView.as_view(), name="task-detail"),
    path("task/<int:pk>/complete/", complete_task, name="task-complete"),
]

app_name = "task"

task/models.py
from django.conf import settings
from django.db import models


class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE,
        related_name="type_tasks",
    )
    assignee = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="assigned_tasks",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="author_tasks",
    )
    PRIORITY_CHOICES = (
        (1, "High"),
        (2, "Medium"),
        (3, "Low"),
    )
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    project = models.ForeignKey(
        "project.Project",
        on_delete=models.CASCADE,
        related_name="tasks",
        null=True,
        blank=True,
    )

task/forms.py
from django import forms

from task.models import Task


class TaskForm(forms.ModelForm):
    priority = forms.ChoiceField(choices=Task.PRIORITY_CHOICES, widget=forms.Select())

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "task_type",
            "deadline",
            "priority",
            "assignee",
        ]
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "datetime-local"}),
            "assignee": forms.CheckboxSelectMultiple(),
            "task_type": forms.RadioSelect(),
        }


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"}),
    )

task/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)

from account.models import Worker
from project.models import Project
from task.forms import TaskForm, SearchForm
from task.models import Task


class Index(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task_pages/home_page.html"
    context_object_name = "tasks"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(assignee=self.request.user)

        filter_type = self.request.GET.get("filter")
        order_by = self.request.GET.getlist("order")
        if filter_type == "uncompleted":
            queryset = queryset.filter(is_completed=False)
        elif filter_type == "completed":
            queryset = queryset.filter(is_completed=True)

        if "priority" in order_by:
            queryset = queryset.order_by("priority")
        elif "date" in order_by:
            queryset = queryset.order_by("deadline")

        return queryset


class CreatedTaskListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "task_pages/created_task_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(CreatedTaskListView, self).get_context_data(**kwargs)

        search = self.request.GET.get("search")

        contex["search"] = SearchForm(initial={"search": search})
        return contex

    def get_queryset(self):
        queryset = Task.objects.filter(author=self.request.user)
        search = self.request.GET.get("search")
        if search:
            return queryset.filter(name__icontains=search)

        return queryset


@login_required
def create_task_view(request, project_id=None):
    project = get_object_or_404(Project, pk=project_id) if project_id else None

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = request.user
            task.project = project
            task.save()
            form.save_m2m()
            return (
                redirect("project:project-detail", pk=project.id)
                if project_id
                else redirect("task:task-list-created")
            )
    else:
        form = TaskForm()
        if project:
            form.fields["assignee"].queryset = Project.objects.get(
                id=project.id
            ).team.members.all()
        else:
            form.fields["assignee"].queryset = Worker.objects.all()

    return render(
        request, "task_pages/task_form.html", {"form": form, "project": project}
    )


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = "task"
    template_name = "task_pages/task_detail.html"


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task_pages/task_form.html"
    success_url = reverse_lazy("task:task-list-created")


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list-created")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.success_url)


def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("task:task"))

templates/task_pages/created_task_list.html
{% extends "base.html" %}

{% block content %}
<div>
    <h2 class="mb-4">My created tasks</h2>
    <a href="{% url "task:task-create" %}" class="btn btn-success mb-3">Create new task</a>
    {% include "includes/search_form.html" %}
    <br>
    {% if tasks %}
        {% include "includes/task.html" %}
    {% else %}
        <p class="text-muted">No created tasks.</p>
    {% endif %}
</div>
{% endblock %}

templates/task_pages/home_page.html
{% extends "base.html" %}

{% block content %}
  <h1>My tasks</h1>
  <form method="get" action="">
    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" id="filterDropdown" data-bs-toggle="dropdown"
              aria-expanded="false">
        Filters & Ordering
      </button>
      <ul class="dropdown-menu" aria-labelledby="filterDropdown">
        <li><h6 class="dropdown-header">Filters</h6></li>
        <li class="dropdown-item">
          <input type="radio" name="filter" value="all" id="filterAll">
          <label for="filterAll">All</label>
        </li>
        <li class="dropdown-item">
          <input type="radio" name="filter" value="completed" id="completed">
          <label for="completed">Completed</label>
        </li>
        <li class="dropdown-item">
          <input type="radio" name="filter" value="uncompleted" id="uncompleted">
          <label for="uncompleted">Uncompleted</label>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>
        <li><h6 class="dropdown-header">Ordering</h6></li>
        <li class="dropdown-item">
          <input type="checkbox" name="order" value="date" id="date">
          <label for="date">Deadline</label>
        </li>
        <li class="dropdown-item">
          <input type="checkbox" name="order" value="priority" id="priority">
          <label for="priority">Priority</label>
        </li>
      </ul>
    </div>
    <button type="submit" class="btn btn-success mt-2">Apply</button>
  </form>


  <div>
    <h3>All tasks</h3>
    {% include "includes/task.html" %}
  </div>

{% endblock %}

templates/task_pages/task_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <div class="card border rounded p-4">
      <h2 class="card-title">{{ task.name }}</h2>
      <p class="text-muted">Deadline: {{ task.deadline }}</p>
      <p class="card-text"><strong>Describe:</strong> {{ task.description }}</p>
      <p><strong>Priority:</strong> {{ task.get_priority_display }}</p>
      <p><strong>Author:</strong> {{ task.author }}</p>
      <p><strong>Assignees:</strong> {{ task.assignee.all|join:", " }}</p>
      <p><strong>Status:</strong> {% if task.is_completed %} Complete {% else %} Incomplete {% endif %}</p>

      {% if task.project %}
        <p><strong>Project:</strong> <a
            href="{% url "project:project-detail" task.project.id %}">{{ task.project.name }}</a></p>
      {% endif %}
      {% if user == task.author %}
        <div class="col-4">
         <a href="{% url "task:task-update" task.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url "task:task-delete" task.id %}" class="btn btn-danger">Delete</a>
        </div>

      {% endif %}
    </div>
  </div>
{% endblock %}

templates/task_pages/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}