core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("teams/", include("team.urls", namespace="team")),
    path("projects/", include("project.urls", namespace="project")),
    path("accounts/", include("account.urls", namespace="account")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.urls import path

from project.views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectDeleteView,
    ProjectUpdateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="project-list"),
    path("create/", ProjectCreateView.as_view(), name="project-create"),
    path("project-detail/<int:pk>", ProjectDetailView.as_view(), name="project-detail"),
    path("delete/<int:pk>", ProjectDeleteView.as_view(), name="project-delete"),
    path("update/<int:pk>", ProjectUpdateView.as_view(), name="project-update"),
]

app_name = "project"

task/urls.py
from django.urls import path

from task.views import (
    Index,
    complete_task,
    CreatedTaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    create_task_view,
)

urlpatterns = [
    path("", Index.as_view(), name="task"),
    path("task/create/", create_task_view, name="task-create"),
    path("task/create/<int:project_id>/", create_task_view, name="task-project-create"),
    path("task/created-list/", CreatedTaskListView.as_view(), name="task-list-created"),
    path("task/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("task/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),
    path("task/detail/<int:pk>", TaskDetailView.as_view(), name="task-detail"),
    path("task/<int:pk>/complete/", complete_task, name="task-complete"),
]

app_name = "task"

project/models.py
from django.conf import settings
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    team = models.ForeignKey(
        "team.Team", on_delete=models.CASCADE, related_name="projects"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="projects"
    )

project/forms.py
from django import forms

from project.models import Project
from team.models import Team


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "team"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields["team"].queryset = Team.objects.filter(author=user)

        self.fields["name"].widget.attrs.update({"class": "form-control"})
        self.fields["description"].widget.attrs.update({"class": "form-control"})
        self.fields["team"].widget.attrs.update({"class": "form-select"})

project/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)

from project.forms import ProjectForm
from project.mixins import TeamListMixin
from project.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    context_object_name = "projects"
    template_name = "project/project_list.html"

    def get_queryset(self):
        return Project.objects.filter(team__members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, TeamListMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "project/project_form.html"
    success_url = reverse_lazy("project:project-list")


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    context_object_name = "project"
    template_name = "project/project_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["tasks"] = self.get_object().tasks.all()

        return context


class ProjectUpdateView(LoginRequiredMixin, TeamListMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "project/project_form.html"
    success_url = reverse_lazy("project:project-list")


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy("project:project-list")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.success_url)

templates/project/project_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h2 class="mb-4">{{ project.name }}</h2>
    <p><strong>Author:</strong> {{ project.author }}</p>
    <p><strong>Describe:</strong> {{ project.description }}</p>

    <h4>Tasks:</h4>
    <ul class="list-group mb-3">

      {% include "includes/task.html" %}

    </ul>

    <a href="{% url "task:task-project-create" project.id %}" class="btn btn-success">Add task</a>

    {% if user == project.author %}
      <a href="{% url "project:project-update" project.id %}" class="btn btn-primary">Edit</a>
      <a href="{% url "project:project-delete" project.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
{% endblock %}

templates/project/project_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} project</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/project/project_list.html
{% extends "base.html" %}



{% block content %}
  <div>
    <h2 class="mb-4">Projects</h2>
    <a href="{% url "project:project-create" %}" class="btn btn-success mb-3">Create project</a>
    {% if projects %}
      <div class="row">
        {% for project in projects %}
          <div class="col-md-4 mb-3">
            <div class="card shadow-sm">
              <div class="card-body">
                <h5 class="card-title">{{ project.name }}</h5>
                <p class="card-text">{{ project.description|truncatewords:20 }}</p>
                <p class="card-text"><strong>Team:</strong> {{ project.team.name }}</p>
                <p class="card-text"><strong>Author:</strong> {{ project.author.username }}</p>
                <a href="{% url "project:project-detail" project.id %}" class="btn btn-primary">Detail</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p class="text-muted">No projects yet.</p>
    {% endif %}
  </div>
{% endblock %}